controllers/StoreController.php
<?php

namespace app\controllers;

use app\models\Bots;
use app\models\DataRecipient;
use app\models\DispatchRegist;
use app\models\Proxy;
use app\models\uploads\UploadItem;
use Yii;
use yii\helpers\Html;
use app\models\Shop;
use app\models\shop\ShopSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\web\UploadedFile;

/**
 * StoreController implements the CRUD actions for Shop model.
 */
class StoreController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Shop models.
     * @return mixed
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->identity->isSuperAdmin()) {
            return $this->redirect(['/shop/']);
        }
        $searchModel = new ShopSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Shop model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'title'=> "Товар : " . $model->name,
                'content'=>$this->renderAjax('view', [
                    'model' => $model,
                ]),
                'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                    Html::a('Изменить',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
            ];
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Creates a new Shop model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $request = Yii::$app->request;
        $model = new Shop();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;

            if($request->isGet){
                return [
                    'title'=> "Создать новый товар",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }else if($model->load($request->post()) && $model->save()){

                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Создать новый товар",
                    'content'=>'<span class="text-success">Создать новый товар</span>',
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::a('Создать еще',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])

                ];
            }else{
                return [
                    'title'=> "Создать новый товар",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Закрыть',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                        Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])

                ];
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Updates an existing Shop model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Изменить",
                    'size' => 'large',
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                return [
                    'forceReload' => '#crud-datatable-pjax',
                    'size' => 'large',
                    'title' => 'Товар : ' . $model->name,
                    'content' => $this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::a('Изменить', ['update', 'id' => $id], ['class' => 'btn btn-primary', 'role' => 'modal-remote'])
                ];
            } else {
                return [
                    'title' => "Изменить",
                    'size' => 'large',
                    'content' => $this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Отмена', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Сохранить', ['class' => 'btn btn-primary', 'type' => "submit"])
                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    public function actionImage($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($request->isGet) {
                return [
                    'title' => "Изменить",
                    'size' => 'large',
                    'content' => $this->renderAjax('_image', [
                        'model' => $model,
                    ]),
                    'footer' => false,
                ];
            } else if ($model->load($request->post()) && $model->save()) {
                return [
                    'size' => 'large',
                    'title' => 'Изображение товара ' . $model->name,
                    'content' => $this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer' => false,
                ];
            } else {
                return [
                    'title' => "Изменить",
                    'size' => 'large',
                    'content' => $this->renderAjax('_image', [
                        'model' => $model,
                    ]),
                    'footer' => false,
                ];
            }
        } else {
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['', 'id' => $model->id]);
            } else {
                return $this->render('_image', [
                    'model' => $model,
                ]);
            }
        }
    }

    public function actionUpload()
    {
        if (Yii::$app->request->isPost) {
            $modelUpload = new UploadItem;
            $modelUpload->fileItem = UploadedFile::getInstance($modelUpload, 'fileItem');
            $modelUpload->upload(Yii::$app->request->post('id'));
            return 1;
        }
    }


    /**
     * Deletes an existing Shop model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        if($bots = Bots::find()->where(['shop_id' => $id])->all()) {
            foreach ($bots as $bot) {
                $bot->shop_id = null;
                $bot->save();
            }
        }

        if($accounts = DispatchRegist::find()->where(['shop_id' => $id])->all()) {
            foreach ($accounts as $account) {
                $account->shop_id = null;
                $account->busy = 1;

views/store/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use app\models\Shop;
use kartik\file\FileInput;
use app\models\DispatchRegist;
use app\models\Proxy;
use app\models\DataRecipient;
use app\models\Bots;
use yii\helpers\ArrayHelper;
use mihaildev\ckeditor\CKEditor;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */
/* @var $form yii\widgets\ActiveForm */


$classMD3 = ['options' => ['class' => 'col-md-3']];
$classMD4 = ['options' => ['class' => 'col-md-4']];
$classMD4Down = ['options' => ['class' => 'col-md-4', 'style' => 'margin-top: 15px']];
$classMD6 = ['options' => ['class' => 'col-md-6']];
$classMD12 = ['options' => ['class' => 'col-md-12']];

$listAccounts = $model->isNewRecord
    ? DispatchRegist::find()->where(['busy' => 1])->all()
    : DispatchRegist::find()->where([
        'OR',
        ['busy' => 1],
        [
            'AND',
            [
                'OR',
                ['busy' => null],
                ['busy' => 0],
            ],
            ['shop_id' => $model->id]
        ]
    ])->all();

$listProxy = $model->isNewRecord
    ? Proxy::find()->where(['busy' => 1])->all()
    : Proxy::find()->where([
        'OR',
        ['busy' => 1],
        [
            'AND',
            [
                    'OR',
                    ['busy' => null],
                    ['busy' => 0]
            ],
            ['shop_id' => $model->id]
        ]
    ])->all();

?>

<div class="shop-form">

    <?php $form = ActiveForm::begin(); ?>
    <?= !$model->isNewRecord ? $form->field($model, 'type')->hiddenInput()->label(false) : null ?>
    <div class="row">
        <?= $form->field($model, 'name', $classMD6)->textInput() ?>
        <?= $form->field($model, 'price', $classMD4)->textInput(['type' => 'number', 'min' => '0.01', 'step' => '0.01']) ?>
        <div class="col-md-2">
            <label class="control-label" for="shop-name">&nbsp;</label>
            <?= $form->field($model, 'access')->checkbox()->label(false) ?>
        </div>
    </div>
    <div class="row js-accounts">
        <?= $model->isNewRecord ? $form->field($model, 'type', $classMD3)->label()->widget(Select2::classname(), [
            'data' => [
                Shop::TYPE_ACCOUNT => 'Аккаунт',
                Shop::TYPE_PROXY => 'Прокси',
                Shop::TYPE_DATABASE => 'База данных',
                Shop::TYPE_BOT => 'Бот',
                Shop::TYPE_ACCOUNT_DATA => 'Аккаунты',
            ],
            'options' => [
                'placeholder' => 'Выберите тип',
                'disabled'
            ],
            'pluginOptions' => [
                'allowClear' => true
            ],
            'pluginEvents' => [
                'change' => "function() {
                if($(this).val() == " . Shop::TYPE_ACCOUNT . ") {
                    $('.js-items').hide();
                    $('.js-items-accounts').show();
                    setEmpty();
                }
                if($(this).val() == " . Shop::TYPE_PROXY . ") {
                    $('.js-items').hide();
                    $('.js-items-proxy').show();
                    setEmpty();
                }
                if($(this).val() == " . Shop::TYPE_DATABASE . ") {
                    $('.js-items').hide();
                    $('.js-items-data').show();
                    setEmpty();
                }
                if($(this).val() == " . Shop::TYPE_BOT . ") {
                    $('.js-items').hide();
                    $('.js-items-bots').show();
                    setEmpty();
                }
            }"
            ]
        ])
            : '<div class="col-md-3"><label class="control-label" for="shop-type">Тип товара</label><span class="form-control">' . $model->getNameType() . '</span></div>' ?>

        <div class="col-md-9 js-items js-items-accounts"
             style="<?= (!$model->isNewRecord && $model->type == Shop::TYPE_ACCOUNT) ? null : 'display: none;' ?>">
            <?= $form->field($model, 'itemsAccounts')->label()->widget(Select2::classname(), [
                'data' => ArrayHelper::map($listAccounts, 'id', 'username'),
                'options' => [
                    'placeholder' => 'Пусто',
                    'multiple' => true,
                    'value' => $model->isNewRecord ? null : $model->getSelectAccounts(),
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ]); ?>
        </div>
        <div class="col-md-9 js-items js-items-proxy"
             style="<?= (!$model->isNewRecord && $model->type == Shop::TYPE_PROXY) ? null : 'display: none;' ?>">
            <?= $form->field($model, 'itemsProxy')->label()->widget(Select2::classname(), [
                'data' => ArrayHelper::map($listProxy, 'id', 'name'),
                'options' => [
                    'placeholder' => 'Пусто',
                    'multiple' => true,
                    'value' => $model->isNewRecord ? null : $model->getSelectProxy(),
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ]); ?>
        </div>
        <div class="col-md-9 js-items js-items-data"
             style="<?= (!$model->isNewRecord && $model->type == Shop::TYPE_DATABASE) ? null : 'display: none;' ?>">
            <?= $form->field($model, 'itemsData')->label()->widget(Select2::classname(), [
                'data' => ArrayHelper::map(DataRecipient::find()->all(), 'id', 'name'),
                'options' => [
                    'placeholder' => 'Пусто',
                    'multiple' => true,
                    'value' => $model->isNewRecord ? null : $model->getSelectData(),
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ]); ?>
        </div>
        <div class="col-md-9 js-items js-items-bots"
             style="<?= (!$model->isNewRecord && $model->type == Shop::TYPE_BOT) ? null : 'display: none;' ?>">
            <?= $form->field($model, 'itemsBots')->label()->widget(Select2::classname(), [
                'data' => ArrayHelper::map(Bots::find()->all(), 'id', 'name'),
                'options' => [
                    'placeholder' => 'Пусто',
                    'multiple' => true,
                    'value' => $model->isNewRecord ? null : $model->getSelectBot(),
                ],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ]); ?>
        </div>
    </div>

    <div class="row">
        <?= $form->field($model, 'description_short', $classMD12)->textInput() ?>
    </div>

    <div class="row">
        <div class="col-md-12">
            <?= $form->field($model, 'accounts_data')->textarea(['rows' => 6]); ?>
        </div>
    </div>

    <?= $form->field($model, 'description_long', $classMD12)->widget(CKEditor::className(), [
        'editorOptions' => [
            'preset' => 'basic', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
            'inline' => false, //по умолчанию false
        ],
    ]); ?>

    <?= $form->field($model, 'additional_info', $classMD12)->widget(CKEditor::className(), [
        'editorOptions' => [
            'preset' => 'basic', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
            'inline' => false, //по умолчанию false
        ],
    ]); ?>

    <?php ActiveForm::end(); ?>

</div>
<script>
    function setEmpty() {
        $('#shop-itemsAccounts').select2('val', 0);
        $('#shop-itemsProxy').select2('val', 0);
        $('#shop-itemsData').select2('val', 0);
        $('#shop-itemsBots').select2('val', 0);
    }
</script>

views/store/_image.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use app\models\Shop;
use kartik\file\FileInput;
use app\models\uploads\UploadItem;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="shop-form">

    <div class="row">
        <div class="col-md-12">
            <?= FileInput::widget([
                'model' => new UploadItem,
                'attribute' => 'fileItem',
                'options' => ['multiple' => false],
                'pluginOptions' => [
                    'showUpload' => true,
                    'uploadUrl' => Url::to(['/store/upload']),
                    'uploadExtraData' => [
                        'id' => $model->id,
                        Yii::$app->getRequest()->csrfParam => Yii::$app->getRequest()->getCsrfToken(),
                    ],
                    'overwriteInitial' => false,
                    'fileActionSettings' => [
                        'showHandle' => false,
                    ],
                    'initialPreview' => $model->image ? [Url::to([$model->image])] : false,
                    'initialPreviewAsData' => $model->image ? true : null,
                ]
            ]); ?>
        </div>
    </div>
</div>

views/store/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\shop\ShopSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="shop-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date_added') ?>

    <?= $form->field($model, 'date_updated') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description_short') ?>

    <?php // echo $form->field($model, 'description_long') ?>

    <?php // echo $form->field($model, 'additional_info') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'access') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'remains') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/store/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Shop */

?>
<div class="shop-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/store/index.php
<?php

use yii\helpers\Html,
    yii\helpers\Url,
    yii\bootstrap\Modal,
    kartik\grid\GridView,
    johnitvn\ajaxcrud\CrudAsset,
    app\components\helpers\FunctionHelper;

/* @var $this yii\web\View */
/* @var $searchModel app\models\shop\ShopSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Shops';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);
?>
    <div class="shop-index">
        <div class="atelier-index">
            <div id="ajaxCrudDatatable">
                <?= GridView::widget([
                    'id' => 'crud-datatable',
                    'dataProvider' => $dataProvider,
//                    'filterModel' => $searchModel,
                    'pjax' => ['enablePushState' => false],
                    'responsiveWrap' => false,
                    'rowOptions' => function ($model) {
                        return ['style' => 'background-color: ' . ($model->access ? '' : '#ffe6b3')];
                    },
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],
                        'name',
                        [
                            'class' => '\kartik\grid\DataColumn',
                            'filter' => false,
                            'attribute' => 'description_short',
                        ],
                        [
                            'class' => '\kartik\grid\DataColumn',
                            'filter' => false,
                            'attribute' => 'price',
                            'hAlign' => GridView::ALIGN_CENTER,
                            'content' => function($model){
                                if($model->price != null){
                                    return "{$model->price} <i class='fa fa-ruble'></i>";
                                }

                                return null;
                            },
                        ],
                        [
                            'class' => '\kartik\grid\DataColumn',
                            'filter' => false,
                            'attribute' => 'remains',
                            'hAlign' => GridView::ALIGN_CENTER,
                            'content' => function ($model) {
                                return $model->getRemains();
                            },

                        ],
                        [
                            'class' => '\kartik\grid\DataColumn',
                            'filter' => false,
                            'attribute' => 'date_added',
                            'content' => function ($model) {
                                return FunctionHelper::dateForForm($model->date_added, 1);
                            },

                        ],
                        [
                            'class' => '\kartik\grid\DataColumn',
                            'filter' => false,
                            'attribute' => 'date_updated',
                            'content' => function ($model) {
                                return $model->date_updated ? FunctionHelper::dateForForm($model->date_updated, 1) : 'не обновлялся';
                            },

                        ],
                        [
                            'class' => 'yii\grid\ActionColumn',
                            'headerOptions' => ['width' => '160'],
                            'template' => '{copy} {view} {image} {update} {delete}',
                            'buttons' => [
                                'copy' => function ($url, $model) {
                                    $url = Url::to(['copy', 'id' => $model->id]);
                                    return Html::a('<span class="fa fa-files-o" style="font-size: 12px;"></span>', $url, [
                                        'class' => 'btn btn-info btn-xs',
                                        'title' => 'Скопировать',
                                        'data-toggle' => 'tooltip'
                                    ]);
                                },
                                'view' => function ($url, $model) {
                                    $url = Url::to(['view', 'id' => $model->id]);
                                    return Html::a('<span class="fa fa-eye" style="font-size: 12px;"></span>', $url, [
                                        'class' => 'btn btn-primary btn-xs',
                                        'role' => 'modal-remote',
                                        'title' => 'Просмотр',
                                        'data-toggle' => 'tooltip'
                                    ]);
                                },
                                'image' => function ($url, $model) {
                                    $url = Url::to(['image', 'id' => $model->id]);
                                    return Html::a('<span class="fa fa-image" style="font-size: 12px;"></span>', $url, [
                                        'class' => 'btn btn-warning btn-xs',
                                        'role' => 'modal-remote',
                                        'title' => 'Изображение',
                                        'data-toggle' => 'tooltip'
                                    ]);
                                },
                                'update' => function ($url, $model) {
                                    $url = Url::to(['update', 'id' => $model->id]);
                                    return Html::a('<span class="fa fa-pencil-square-o" style="font-size: 12px;"></span>', $url, [
                                        'class' => 'btn btn-success btn-xs',
                                        'role' => 'modal-remote',
                                        'title' => 'Изменить',
                                        'data-toggle' => 'tooltip'
                                    ]);
                                },
                                'delete' => function ($url, $model) {
                                    $url = Url::to(['delete', 'id' => $model->id]);
                                    return Html::a('<span class="fa fa-trash-o" style="font-size: 12px;"></span>', $url, [
                                        'class' => 'btn btn-danger btn-xs',
                                        'role' => 'modal-remote',
                                        'data-confirm' => true,
                                        'title' => 'Подтвердите Удаление',
                                        'data-toggle' => 'tooltip',
                                        'data-method' => 'post',
                                        'data-confirm-title' => 'Подтвердите действие',
                                        'data-confirm-message' => 'Вы уверены что хотите удалить этого элемента?',
                                    ]);
                                },
                            ],
                        ]

                    ],

                    'toolbar' => [
                        ['content' =>
                            Html::a('Создать', ['create'], ['role' => 'modal-remote', 'title' => 'Создать', 'class' => 'btn btn-info']) .
                            Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''], ['data-pjax' => 1, 'class' => 'btn btn-default', 'title' => 'Обновить']) .
                            '{toggleData}'
                        ],
                    ],
                    'striped' => true,
                    'condensed' => true,
                    'responsive' => true,
                    'toolbarContainerOptions' => ['style' => 'margin-top: 15px;'],
                    'panel' => [
                        'type' => 'default',
                        'heading' => '<i class="glyphicon glyphicon-list"></i> Товары',
                        'before' => '',
                        'after' => false,
                    ]
                ]); ?>
            </div>
        </div>
    </div>
<?php Modal::begin([
    "id" => "ajaxCrudModal",
    "footer" => "",// always need it for jquery plugin
]) ?>
<?php Modal::end(); ?>

views/store/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */

?>
<div class="shop-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/store/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Shop */

$this->title = $model->name;

?>
<div class="panel ">
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-3" style="border: 1px solid #c2bec4; border-radius: 10px">
                <?= Html::img([$model->image], ['style' => 'width: 100%']) ?>
            </div>
            <div class="col-xs-9">
                <h2><?= $model->name ?></h2>
                <h3 class="text-success"><?= number_format($model->price, 2, ',', ' ') ?> <i class="fa fa-rub"></i></h3>
                <h4 style="padding: 30px 0px"> <?= $model->description_short ?></h4>
                <div class="row">
                    <div class="col-md-2">
                        <?= Html::input('number', 'count', 1, ['class' => 'form-control', 'min' => 1, 'step' => 1]); ?>
                    </div>
                    <div class="col-md-2">
                        <?= Html::button('Купить сейчас', ['class' => 'btn btn-success']); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="padding: 30px 0px;">
            <?php
            echo \yii\bootstrap\Tabs::widget([
                'items' => [
                    [
                        'label' => 'Описание',
                        'content' => '<div style="padding: 20px 10px">' . $model->description_long . '</div>',
                        'active' => true,
                    ],
                    [
                        'label' => 'Дополнительная информация',
                        'content' => '<div style="padding: 20px 10px">' . $model->additional_info . '</div>',
                    ],

                ]
            ]);

            ?>

        </div>
    </div>
</div>