controllers/TradeController.php
<?php

namespace app\controllers;

use app\components\AccountsDataPurchase;
use app\components\helpers\FunctionHelper;
use app\models\AccountingReport;
use app\models\Bots;
use app\models\BotsDialogs;
use app\models\Companies;
use app\models\DataRecipient;
use app\models\DispatchRegist;
use app\models\Proxy;
use app\models\Settings;
use app\models\Shop;
use app\modules\api\controllers\ClientController;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * BotsController implements the CRUD actions for Bots model.
 */
class TradeController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     * @throws \Exception
     */
    public function actionIndex()
    {
        $items = Shop::find()->where(['access' => 1])->all();
        return $this->render('index', [
            'items' => $items,
        ]);
    }

    public function actionItem($id)
    {
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model,
        ]);
    }

    public function actionBuy()
    {
        $transCommited = false;

        Yii::$app->response->format = Response::FORMAT_JSON;
        $statusCode = 200;
        $request = Yii::$app->request;
        if (Yii::$app->request->isAjax) {

            if ($request->post('count') < 1) {
                return false;
            }

            $transaction = Yii::$app->db->beginTransaction();
            $item = $this->findModel($request->post('item'));
            $company = Companies::findOne(FunctionHelper::getCompanyId());
            $allPrice = $item->price * $request->post('count');
            if ($item->getRemains() < $request->post('count')) {
                $buy = false;
                $reason = 'Товара нет в наличии';
                $statusCode = 400;
                $count = $item->getRemains();
            } else {
                if ($company->general_balance < $allPrice) {
                    $buy = false;
                    $reason = 'Недостаточно средств';
                    $statusCode = 402;
                    $count = $item->getRemains();
                } else {

                    $buy = true;

                    if($item->type != Shop::TYPE_ACCOUNT_DATA) {
                        $company->general_balance -= $allPrice;
                        if ($company->save()) {
                            $accountReport = new AccountingReport([
                                'company_id' => $company->id,
                                'operation_type' => AccountingReport::TYPE_OUTPUT_SHOP,
                                'amount' => $allPrice,
                                'description' => 'Покупка товара  "' . $item->name . '" (' . $request->post('count') . ' eд.).',
                            ]);
                            $accountReport->save();
                        }
                    }

                    switch ($item->type) {
                        case Shop::TYPE_ACCOUNT:
                            if ($accounts = DispatchRegist::find()->where(['shop_id' => $item->id])->all()) {
                                $i = 0;
                                foreach ($accounts as $account) {
                                    if ($i >= $request->post('count')) {
                                        break;
                                    }
                                    $account->company_id = $company->id;
                                    $account->shop_id = null;
                                    $account->save();
                                    $i++;
                                }
                            }
                            break;
                        case Shop::TYPE_PROXY:
                            if ($proxys = Proxy::find()->where(['shop_id' => $item->id])->all()) {
                                $i = 0;
                                foreach ($proxys as $proxy) {
                                    if ($i >= $request->post('count')) {
                                        break;
                                    }
                                    $proxy->companyId = $company->id;
                                    $proxy->shop_id = null;
                                    $proxy->save();
                                    $i++;
                                }
                            }
                            break;
                        case Shop::TYPE_BOT:
                            if ($bots = Bots::find()->where(['shop_id' => $item->id])->all()) {
                                $i = 0;
                                foreach ($bots as $bot) {
                                    if ($i >= $request->post('count')) {
                                        break;
                                    }
                                    $cloneBot = new Bots([
                                        'name' => $bot->name . ' (' . date('Y-m-d H:i:s') . ')',
                                        'companyId' => $company->id,
                                    ]);
                                    $cloneBot->save();
                                    if ($dialogModel = BotsDialogs::find()->where(['botId' => $bot->id])->all()) {
                                        foreach ($dialogModel as $dialog) {
                                            $cloneDialog = new BotsDialogs([
                                                'botId' => $cloneBot->id,
                                                'stepNumber' => $dialog->stepNumber,
                                                'result' => $dialog->result,
                                                'notify' => $dialog->notify,
                                                'anyAnswer' => $dialog->anyAnswer,
                                            ]);
                                            $cloneDialog->save();
                                        }
                                    }
                                    $i++;
                                }
                            }
                            break;
                        case Shop::TYPE_DATABASE:
                            if ($dataBases = DataRecipient::find()->where(['shop_id' => $item->id])->all()) {
                                $i = 0;
                                foreach ($dataBases as $dataBase) {
                                    if ($i >= $request->post('count')) {
                                        break;
                                    }

                                    $cloneDataBases = new DataRecipient([
                                        'name' => $dataBase->name . ' (' . date('Y-m-d H:i:s') . ')',
                                        'company_id' => $company->id,
                                        'file' => $dataBase->file,
                                        'type' => DataRecipient::TYPE_PAYD,
                                        'description' => 'Куплена ' . date('d.m.Y H:i:s'),
                                        'count' => $dataBase->count,
                                    ]);
                                    $cloneDataBases->save();
                                    $i++;
                                }
                            }
                            break;
                        case Shop::TYPE_ACCOUNT_DATA:
                            if($statusCode != 200){
                                throw new HttpException($statusCode);
                            }

                            $count = $request->post('count');
                            $purchase = AccountsDataPurchase::makePurchase($item, $company->id, $count);
                            $purchasedAccounts = $purchase->purchasedAccounts;

                            if(is_dir('tmp') == false)
                            {
                                mkdir('tmp');
                            }


                            $accounts = $purchasedAccounts;

                            $result = [
                                'errorText' => '',
                            ];
                            try{
                                foreach ($accounts as $account)
                                {
                                    $account = explode(":", $account);

                                    $dispatchRegist = new DispatchRegist();
                                    $dispatchRegist->login = trim($account[0]);
                                    $dispatchRegist->password = trim($account[1]);
                                    $dispatchRegist->company_id = $company->id;
                                    $dispatchRegist->data = date('Y-m-d H:i:s');
                                    $dispatchRegist->save();
//                                    if($dispatchRegist->token == null){
//                                        $clientIdSetting = Settings::findByKey('app_id');
//                                        $scopeSetting = Settings::findByKey('scope');
//                                        if($clientIdSetting == null || $scopeSetting == null){
//                                            throw new HttpException(500, 'Ошибка параментров настроек администратора');
//                                        }

views/trade/index.php
<?php
use Yii,
    yii\helpers\Html,
    yii\helpers\Url,
    app\models\Shop;
use yii\bootstrap\Modal;


$this->title = 'Магазин';

$this->params['breadcrumbs'][] = ['label' => $this->title];

$this->registerJsFile("js/plugins/equalheights/equalheights.min.js", [
    'depends' => [\app\assets\AppAsset::className()],
], 'js-equals-heights');
$this->registerCssFile("css/pages/trade.css", [
    'depends' => [\app\assets\AppAsset::className()],
], 'css-page');

?>
<?php if(\app\components\helpers\FunctionHelper::getCompanyModel()->isBonusBalanceActive): ?>
    <div class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <strong>Внимание!</strong> Покупки в магазине не могут быть оплачены бонусами
    </div>
<?php endif; ?>
<div class="panel shop-panel">
    <div class="panel-body">
        <div class="row" style="padding: 20px; 5px;">
            <?php
            if ($items) {
                $col = 0;
                foreach ($items as $item) {
                    $remains = $item->getRemains();
                    $col++;
                    if ($col == 1) {
                        ?>
                        <div class="row">
                        <?php
                    }
                    ?>
                    <div class="col-md-3" style="padding-bottom: 30px;">
                        <form id="form-<?= $item->id ?>">
                            <input type="hidden" name="item" value="<?= $item->id ?>">
                            <div style="padding: 10px; border-radius: 10px; border: 1px solid #c2bec4; box-shadow: 0 5px 15px rgba(0,0,0,0.3);">
                                <div class="prod-info">
                                    <h3><?= Html::a($item->name, Url::to(['trade/item/', 'id' => $item->id]), ['target' => '_blank']) ?></h3>
                                    <h4 class="shop-card-description"><?= Html::a($item->description_short, Url::to(['trade/item/', 'id' => $item->id]), ['target' => '_blank']) ?></h4>


                                </div>
                                <div>
                                    <?php
                                    if ($item->type == Shop::TYPE_ACCOUNT_DATA || $item->type == Shop::TYPE_ACCOUNT || $item->type == Shop::TYPE_PROXY) {
                                        ?>
                                        В наличии: <span class="count-item-<?= $item->id ?>"><?= $remains ?></span>
                                        <?php
                                    } else {
                                        echo '&nbsp';
                                    }
                                    ?>
                                </div>
                                <div class="shop-card-full-description">
                                    <?=$item->description_long?>
                                </div>
                                <div class="row shop-card-floor">
                                    <div class="col-xs-6" style="padding-left: 0;">
                                        <h4 class="text-success js-price-<?= $item->id ?>" style="margin-top: 6px;">
                                            <?= number_format($item->price, 2, ',', ' ') ?>
                                            <i class="fa fa-ruble"></i>
                                            <br/>
                                            <span style="font-size: 12px" class="js-alert-<?= $item->id ?>"></span>
                                        </h4>
                                    </div>
                                    <div class="col-xs-3">
                                        <?php
                                        if ($item->type == Shop::TYPE_ACCOUNT_DATA || $item->type == Shop::TYPE_ACCOUNT || $item->type == Shop::TYPE_PROXY) {
                                            ?>
                                            <?= Html::input('hidden', 'count', 1, ['class' => 'js-count-' . $item->id . ' form-control', 'min' => 1, 'max' => 1, 'step' => 1]); ?>
                                            <?php
                                        } else {
                                            echo '<input type="hidden" name="count" value="1" class="js-count-' . $item->id . '">';
                                        }
                                        ?>

                                    </div>
                                    <?php if($item->type != Shop::TYPE_ACCOUNT_DATA){ ?>
                                        <div class="col-xs-2 text-right item" data-key="<?= $item->id ?>"
                                             data-name="<?= $item->name ?>" data-price="<?= $item->price ?>">
                                            <?= Html::button('<i class="fa fa-shopping-cart"></i>', [
                                                'class' => 'btn btn-success js-buy',
                                                'data-loading-text' => "<i class='fa fa-circle-o-notch fa-spin'></i>",
                                            ]); ?>
                                        </div>
                                    <?php } else { ?>
                                        <div class="col-xs-2 text-right item-accounts" data-key="<?= $item->id ?>"
                                             data-name="<?= $item->name ?>" data-price="<?= $item->price ?>">
                                            <?= Html::button('<i class="fa fa-shopping-cart"></i>', [
                                                'class' => 'btn btn-success js-buy',
                                                'data-loading-text' => "<i class='fa fa-circle-o-notch fa-spin'></i>",
                                            ]); ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </form>
                    </div>

                    <?php
                    if ($col == 4) {
                        $col = 0;
                        ?>
                        </div>
                        <?php
                    }
                }
            }
            ?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxErrorModal",
    'header' => 'Ошибка',
    'bodyOptions' => ['id' => 'ajaxErrorModalBody', 'class' => 'modal-body'],
    "footer"=>"",// always need it for jquery plugin
])?>
    <p>
    <div id="error-alert" class="alert alert-danger" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    </div>
    </p>
<?php Modal::end(); ?>
<?php

$redirectUrl = Url::to(['/dispatch-regist/index']);
$buyUrl = Url::to(['/trade/buy']);
$script = <<< JS
    $(function () {
        $('.shop-card-full-description').equalHeights();
        $('.item').on('click', '.js-buy', function () {
            var button = $(this);
            var id = $(this).closest('div').data('key');
            var name = $(this).closest('div').data('name');
            var price = $(this).closest('div').data('price');
            var count = $('.js-count-' + id).val();
            price = price * count;
            var data = $('#form-' + id).serialize();

            // setTimeout(function(){
                
              // $(this).off('click', function(event){
              //     console.log(event);
              //    
              //     $(".item-accounts").each(function(e) {
              //           e.unbind();
              //     });
              // });
            // }, 1000);
            
            if (confirm("Купить " + count + " " + name + " за " + price + " рублей?")) {

                $.ajax({
                    url: '{$buyUrl}',
                    type: 'POST',
                    data: data,
                    dataType: 'json',
                    beforeSend: function () {
                        button.button('loading');
                        $('#background-wait').show();
                    },
                    success: function (json) {
                        $('#background-wait').hide();
                        if (json.buy) {
                            $('.js-alert-' + id).html(json.reason);
                            $('.js-alert-' + id).html(json.reason);
                            $('.count-item-' + id).html(json.count);
                            $('.js-alert-' + id).removeClass('text-danger').addClass('text-success');
                            $('.js-price-' + id).removeClass('text-danger').addClass('text-success');
                        } else {
                            $('.js-alert-' + id).html(json.reason);
                            $('.js-alert-' + id).removeClass('text-success').addClass('text-danger');
                            $('.js-price-' + id).removeClass('text-success').addClass('text-danger');

                        }
                        
                        button.button('reset');
                        // window.location = '$redirectUrl';
                    }
                });
            }
            ;
        });
        $('.item-accounts').on('click', '.js-buy', function () {
                var button = $(this);
                var id = $(this).closest('div').data('key');
                var name = $(this).closest('div').data('name');
                var price = $(this).closest('div').data('price');
                var count = $('.js-count-' + id).val();
                price = price*count;
                var data = $('#form-' + id).serialize();
    
                if (confirm('Купить ' + count + ' ' + name + ' за ' + price + ' рублей?')) {
                    $.ajax({
                        url: '{$buyUrl}',
                        type: 'POST',
                        data: data,
                        dataType: 'json',
                        // xhrFields: {
                        //     responseType: 'blob'
                        // },
                        beforeSend: function () {
                            button.button('loading');
                            $('#background-wait').show();
                        },
                        success: function (responseData, textStatus, xhr) {
                            if(responseData.errorText == ''){
                                window.location = '$redirectUrl';
                            } else {
                                $('#error-alert').text(responseData.errorText);
                                $('#ajaxErrorModal').modal();
                            }
                        },
                        error: function(xhr, textStatus, errorThrown){
                            if(xhr.status == 402)
                            {
                                alert('Недостаточно средств');
                            }
                            if(xhr.status == 400)
                            {
                                alert('Товара нет в наличии');
                            }
                        },
                    }).always(function(){
                        button.button('reset');
                        // window.location = '$redirectUrl';
                        
                        // $(this).unbind('click');
                        // console.log($(this));
                    });
                    // jQuery._data( $(this), "events" );
                }
            });
        
            // setTimeout(function(){
                // console.log($('.item-accounts').event('click'));
            // },1000);
          // $(".item-accounts").off('click', function(event){
          //     console.log(event);
          //    
          //     $(".item-accounts").each(function(e) {
          //           e.unbind();
          //     });
          // });
    });
JS;

$this->registerJs($script, \yii\web\View::POS_READY);

views/trade/view.php
<?php
use Yii,
    yii\helpers\Html,
    yii\helpers\Url,
    yii\bootstrap\Tabs;


$this->title = $model->name;
$remains = $model->getRemains();

$this->params['breadcrumbs'][] = ['label' => $this->title];
?>


<div class="panel">

    <div class="panel-body">
        <form id="form-<?= $model->id ?>">
            <input type="hidden" name="item" value="<?= $model->id ?>">
            <div class="row"  style="padding-left: 20px">
                <div class="col-xs-12">
                    <h2><?= $model->name ?></h2>
                    <h3 class="text-success js-price-<?= $model->id ?>">
                        <?= number_format($model->price, 2, ',', ' ') ?>
                        <i class="fa fa-rub"></i>
                        <br/>
                        <span style="font-size: 12px" class="js-alert-<?= $model->id ?>"></span>
                    </h3>
                    <div>
                        В наличии: <span id="countItem"><?= $remains ?></span>
                    </div>
                    <h4 style="padding: 30px 0px"> <?= $model->description_short ?></h4>
                    <div class="row">
                        <div class="col-md-2">
                            <?= Html::input('hidden', 'count', 1, ['class' => 'js-count form-control', 'min' => 1, 'max' => 1, 'step' => 1]); ?>
                        </div>
                        <div class="col-md-2 item" data-key="<?= $model->id ?>" data-name="<?=$model->name?>" data-price="<?=$model->price?>">
                            <?= Html::button('Купить сейчас', ['class' => 'btn btn-success js-buy']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="padding: 30px 20px; margin-top: 50px;">
                <?php
                echo \yii\bootstrap\Tabs::widget([
                    'items' => [
                        [
                            'label' => 'Описание',
                            'content' => '<div style="padding: 20px 10px">' . $model->description_long . '</div>',
                            'active' => true,
                        ],
                        [
                            'label' => 'Дополнительная информация',
                            'content' => '<div style="padding: 20px 10px">' . $model->additional_info . '</div>',
                        ],
                    ]
                ]); ?>
            </div>
        </form>
    </div>
</div>

<?php

$buyUrl = Url::to(['/trade/buy']);

if($model->type != \app\models\Shop::TYPE_ACCOUNT_DATA){
    $script = <<< JS
    $(function () {
        $('.item').on('click', '.js-buy', function () {
            var id = $(this).closest('div').data('key');
            var name = $(this).closest('div').data('name');
            var price = $(this).closest('div').data('price');
            var count = $('.js-count').val();
            price = price*count;
            var data = $('#form-' + id).serialize();

            if (confirm("Купить " + count + " " + name + " за " + price + " рублей?")) {
                $.ajax({
                    url: '{$buyUrl}',
                    type: 'POST',
                    data: data,
                    dataType: 'json',
                    beforeSend: function () {
                        $('#background-wait').show();
                    },
                    success: function (responseData) {
                       $('#background-wait').hide();
                       if (json.buy) {
                           location.reload()
                       } else {
                           $('.js-alert-' + id).html(json.reason);
                           $('.js-alert-' + id).removeClass('text-success').addClass('text-danger');
                           $('.js-price-' + id).removeClass('text-success').addClass('text-danger');
                       }
                    }
                });
            }
        });
    });
JS;
} else {
    $script = "
        $(function () {
            $('.item').on('click', '.js-buy', function () {
                var id = $(this).closest('div').data('key');
                var name = $(this).closest('div').data('name');
                var price = $(this).closest('div').data('price');
                var count = $('.js-count').val();
                price = price*count;
                var data = $('#form-' + id).serialize();
    
                if (confirm('Купить ' + count + ' ' + name + ' за ' + price + ' рублей?')) {
                    $.ajax({
                        url: '{$buyUrl}',
                        type: 'POST',
                        data: data,
                        xhrFields: {
                            responseType: 'blob'
                        },
                        beforeSend: function () {
                            $('#background-wait').show();
                        },
                        success: function (responseData, textStatus, xhr) {
                            var a = document.createElement('a');
                            var url = window.URL.createObjectURL(responseData);
                            a.href = url;
                            a.download = 'Аккаунты.txt';
                            a.click();
                            window.URL.revokeObjectURL(url);   
                        },
                        error: function(xhr, textStatus, errorThrown){
                            if(xhr.status == 402)
                            {
                                alert('Недостаточно средств');
                            }
                            if(xhr.status == 400)
                            {
                                alert('Товара нет в наличии');
                            }
                        },
                    });
                }
            });
        });
    ";
}

$this->registerJs($script, \yii\web\View::POS_READY);

?>