models/GlobalMessages.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "global_messages".
 *
 * @property int $id
 * @property string $name Наименование
 * @property resource $text Текст
 * @property int $views_count Кол-во просмотров
 * @property string $created_at
 */
class GlobalMessages extends \yii\db\ActiveRecord
{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => null,
                'value' => date('Y-m-d H:i:s'),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'global_messages';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'text'], 'required'],
            [['text'], 'string'],
            [['views_count'], 'integer'],
            [['created_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'text' => 'Текст',
            'views_count' => 'Просмотры',
            'created_at' => 'Дата и время',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
        if($insert){
            Users::updateAll(['messages_read_status' => false]);
        }
    }

    /**
     * Возращает последнюю запись
     * @return array|\yii\db\ActiveRecord
     */
    public static function getLastMessage()
    {
        return self::find()->orderBy('created_at desc')->one();
    }
}

controllers/GlobalMessagesController.php
<?php

namespace app\controllers;

use app\filters\PermissionsFilter;
use app\models\Users;
use Yii;
use app\models\GlobalMessages;
use app\models\GlobalMessagesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;

/**
 * GlobalMessagesController implements the CRUD actions for GlobalMessages model.
 */
class GlobalMessagesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all GlobalMessages models.
     * @return mixed
     */
    public function actionIndex()
    {

            if (!Yii::$app->user->identity->isSuperAdmin()) {
                $items = GlobalMessages::find()->orderBy(['id' => SORT_DESC])->all();
                return $this->render('list', [
                    'items' => $items,
                ]);
            }



        $searchModel = new GlobalMessagesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->sort->defaultOrder = ['id' => SORT_DESC];



        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionItem($id)
    {
        $model = $this->findModel($id);
        return $this->render('list-view', [
            'model' => $model,
        ]);
    }



    /**
     * Displays a single GlobalMessages model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {



        $request = Yii::$app->request;
        $model =$this->findModel($id);
        $model->views_count++;
        $model->save(false);
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> $model->name,
                    'content'=>$this->renderAjax('view', [
                        'model' => $model ,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Edit',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
        }else{
            return $this->render('view', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Creates a new GlobalMessages model.
     * For ajax request will return json object
     * and for non-ajax request if creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new GlobalMessages();  

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> "Create new GlobalMessages",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> "Create new GlobalMessages",
                    'content'=>'<span class="text-success">Create GlobalMessages success</span>',
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Create More',['create'],['class'=>'btn btn-primary','role'=>'modal-remote'])
        
                ];         
            }else{           
                return [
                    'title'=> "Create new GlobalMessages",
                    'content'=>$this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])
        
                ];         
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('create', [
                    'model' => $model,
                ]);
            }
        }
       
    }

    /**
     * Updates an existing GlobalMessages model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($request->isGet){
                return [
                    'title'=> $model->name,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])
                ];         
            }else if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'title'=> $model->name,
                    'content'=>$this->renderAjax('view', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                            Html::a('Edit',['update','id'=>$id],['class'=>'btn btn-primary','role'=>'modal-remote'])
                ];    
            }else{
                 return [
                     'title'=> $model->name,
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            /*
            *   Process for non-ajax request
            */
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    /**
     * Delete an existing GlobalMessages model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }


    }

     /**
     * Delete multiple existing GlobalMessages model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBulkDelete()
    {        
        $request = Yii::$app->request;
        $pks = explode(',', $request->post( 'pks' )); // Array or selected records primary keys
        foreach ( $pks as $pk ) {
            $model = $this->findModel($pk);
            $model->delete();
        }

        if($request->isAjax){
            /*
            *   Process for ajax request
            */
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            /*
            *   Process for non-ajax request
            */
            return $this->redirect(['index']);
        }
       
    }

    /**
     * Finds the GlobalMessages model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return GlobalMessages the loaded model

views/global-messages/_columns.php
<?php
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
        // [
        // 'class'=>'\kartik\grid\DataColumn',
        // 'attribute'=>'id',
    // ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
//    [
//        'class'=>'\kartik\grid\DataColumn',
//        'attribute'=>'text',
//    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'views_count',
        'hAlign' => \kartik\grid\GridView::ALIGN_CENTER,
    ],
     [
         'class'=>'\kartik\grid\DataColumn',
         'attribute'=>'created_at',
         'format' => ['date', 'php:d.m.Y H:i:s'],
     ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Are you sure?',
                          'data-confirm-message'=>'Are you sure want to delete this item'], 
    ],

];   

views/global-messages/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\GlobalMessages */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="global-messages-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'text')->widget(\mihaildev\ckeditor\CKEditor::class, [

    ]) ?>

	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/global-messages/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\GlobalMessages */

?>
<div class="global-messages-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/global-messages/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\GlobalMessagesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Рассылка';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="global-messages-index">
    <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'toolbar'=> [
                ['content'=>
                    Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Create new Global Messages','class'=>'btn btn-default']).
                    Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Reset Grid']).
                    '{toggleData}'.
                    '{export}'
                ],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'toolbarContainerOptions' => ['style' => 'margin-top: 15px;'],
            'panel' => [
                'type' => 'primary', 
                'heading' => '<i class="glyphicon glyphicon-list"></i> Рассылка',
                'after'=>BulkButtonWidget::widget([
                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All',
                                ["bulk-delete"] ,
                                [
                                    "class"=>"btn btn-danger btn-xs",
                                    'role'=>'modal-remote-bulk',
                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'data-request-method'=>'post',
                                    'data-confirm-title'=>'Are you sure?',
                                    'data-confirm-message'=>'Are you sure want to delete this item'
                                ]),
                        ]).                        
                        '<div class="clearfix"></div>',
            ]
        ])?>
    </div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/global-messages/list.php
<?php

use johnitvn\ajaxcrud\CrudAsset;
use Yii,
    yii\helpers\Html,
    yii\helpers\Url,
    app\models\Shop;
use yii\bootstrap\Modal;


$this->title = 'Новости';

$this->params['breadcrumbs'][] = ['label' => $this->title];

$this->registerJsFile("js/plugins/equalheights/equalheights.min.js", [
    'depends' => [\app\assets\AppAsset::className()],
], 'js-equals-heights');
$this->registerCssFile("css/pages/trade.css", [
    'depends' => [\app\assets\AppAsset::className()],
], 'css-page');

CrudAsset::register($this);
?>

<div class="panel shop-panel">
    <div class="panel-body">
        <div class="row" style="padding: 20px; 5px;">
            <?php
            if ($items) {
                $col = 0;
                foreach ($items as $item) {
                    $remains = 0;
                    $col++;
                    if ($col == 1) {
                        ?>
                        <div class="row">
                        <?php
                    }
                    ?>
                    <div class="col-md-3" style="padding-bottom: 30px;">
                        <form id="form-<?= $item->id ?>">
                            <input type="hidden" name="item" value="<?= $item->id ?>">
                            <div style="padding: 10px; border-radius: 10px; border: 1px solid #c2bec4; box-shadow: 0 5px 15px rgba(0,0,0,0.3);">
                                <div class="prod-info">
                                    <h4>
                                        <?= Html::a($item->name, Url::to(['global-messages/view', 'id' => $item->id]), [ 'role' => "modal-remote", 'data-toggle' => "tooltip", 'data-original-title' =>"Подробнее"]) ?>
                                    </h4>
                                    <h5 class="shop-card-description">
                                        <?= Html::a($item->created_at, Url::to(['global-messages/view', 'id' => $item->id]), [ 'role' => "modal-remote", 'data-toggle' => "tooltip", 'data-original-title' =>"Подробнее"]) ?>

                                    </h5>

                                </div>
                                <div class="shop-card-full-description">
                                    <?php
                                        $text = substr($item->text,0,600);
                                        $text = str_replace(" height=\"300\" ", " height=\"150\" ",  $text);
                                        $text = str_replace("width=\"550\"", "width=\"237\"", $text);
                                        echo $text;
                                    ?>
                                </div>
                                <div class="row shop-card-floor">
                                    <div class="col-xs-6" style="padding-left: 0;padding-top: 2px;">
                                        <h6 class="text-success-<?= $item->id ?>" style="margin-top: 6px;">
                                            <?=$item->views_count ?>
                                            <i class="fa fa-eye"></i>
                                            <br/>
                                            <span style="font-size: 12px" class="js-alert-<?= $item->id ?>"></span>
                                        </h6>
                                    </div>
                                        <div class="col-xs-2 text-right item-accounts">
                                            <a class="btn btn-success js-buy" href="/global-messages/view?id=<?=$item->id?>" title="" role="modal-remote" data-toggle="tooltip" data-original-title="Подробнее">Подробнее</a>
                                        </div>
                                </div>
                            </div>
                        </form>
                    </div>

                    <?php
                    if ($col == 4) {
                        $col = 0;
                        ?>
                        </div>
                        <?php
                    }
                }
            }
            ?>
        </div>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>

views/global-messages/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\GlobalMessages */
?>
<div class="global-messages-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/global-messages/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\GlobalMessages */
?>
<div class="global-messages-view">


    <?=$model->text?>
    <div class="panel-body">
        <table id="w0" class="table table-striped table-bordered detail-view">
            <tbody>
            <tr><th>Наименование</th><td><?=$model->name?></td></tr>
            <tr><th>Просмотры</th><td><?=$model->views_count?></td></tr>
            <tr><th>Дата и время</th><td><?=$model->created_at?></td></tr>
            </tbody>
        </table>
    </div>

</div>