controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Rates;
use app\models\ReferalRedirects;
use app\models\Slider;
use app\models\Users;
use app\models\Settings;
use app\modules\api\controllers\ClientController;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\IdentityInterface;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

use app\models\Logs;
use app\models\RegisterForm;
use app\models\ResetPasswordForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->render('index');
        } else {
            return $this->redirect(['site/login']);
        }
    }

    /**
     * Login action.
     *
     * @return Response|string
     */

    public function actionAvtorizatsiya()
    {
        if (isset(Yii::$app->user->identity->id)) {
            return $this->render('error');
        } else {
            Yii::$app->user->logout();
            $this->redirect(['login']);
        }
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        if (Yii::$app->request->get('ref')) {
            Yii::$app->response->cookies->add(new \yii\web\Cookie(['name' => 'referal', 'value' => Yii::$app->request->get('ref')]));
        }

        $slider = Slider::find()->where(['enable' => 1])->orderBy('sort asc')->all();

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $log = new Logs([
                'user_id' => Yii::$app->user->id,
                'event_datetime' => date('Y-m-d H:i:s'),
                'event' => Logs::EVENT_USER_AUTHORIZED,
            ]);
            $log->description = $log->generateEventDescription();
            $log->save();
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
            'slider' => $slider,
        ]);
    }

    public function actionVk()
    {

        if (isset($_GET['code'])) {
            $result = false;
            $client_secret = 'wsQ8HFU3yGx9wvAXSAua';
            $client_id = '6651556';
            $redirect_uri = 'https://demo.teo-send.ru/site/vk';
            $params = array(
                'client_id' => $client_id,
                'client_secret' => $client_secret,
                'code' => $_GET['code'],
                'redirect_uri' => $redirect_uri
            );
            $token_url =  'https://api.vk.com/oauth/access_token?client_id='.$client_id.'&client_secret='.$client_secret.'&code='.$_GET['code'].'&redirect_uri='.$redirect_uri;
            $params = json_decode(@file_get_contents($token_url));
            if (!$params) {
                $this->redirect(['login']);
            }
            $user_id = $params->user_id;
            $request_params = array(
                'uid' => $user_id,
                'fields' => 'photo,nickname',
                'v' => '5.52',
                'access_token' => $params->access_token,
                'sig' => md5('/method/getProfiles?uid='.$user_id.'&fields=photo,nickname&v=5.52&access_token='.$params->access_token.$params->secret)
            );
            $get_params = http_build_query($request_params);
            $result = json_decode(file_get_contents('https://api.vk.com/method/getProfiles?'. $get_params));
            echo "<pre>";
            print_r($result);
            echo "</pre>";

            $user = Users::find()->where([ 'vk_id' => $result->response[0]->id])->one();

            if($user)
            {
                $login = new LoginForm();
                $login->username = $user->login;
                $login->password = $user->auth_key;
                $login->login();
                return $this->goBack();
            } else {
                $model = new RegisterForm();
                $model->rate_id = Rates::getDefaultRate();
                $model->fio = $result->response[0]->last_name.' '. $result->response[0]->first_name;
                $model->login = $result->response[0]->id.'@mail.ru';
                // $model->telephone = $result->response[0]->id;
                $model->password = md5($result->response[0]->id);
                $model->telephone = ''.$result->response[0]->id;
                $model->vk_id = ''.$result->response[0]->id;
                $model->data_processing = 1;
                $model->register();
                $login = new LoginForm();
                $login->username = $result->response[0]->id;
                $login->password = md5($result->response[0]->id);
                if ($login->login()){
                    return $this->goBack();
                }
            }

        }

        $this->redirect(['login']);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        $this->redirect(['login']);
    }

    public function actionMenuPosition()
    {
        $session = Yii::$app->session;
        if ($session['menu'] == null | $session['menu'] == 'large') $session['menu'] = 'small';
        else $session['menu'] = 'large';

        return $session['menu'];
    }

    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        if (Yii::$app->request->get('ref')) {
            Yii::$app->response->cookies->add(new \yii\web\Cookie(['name' => 'referal', 'value' => Yii::$app->request->get('ref')]));
        }

        $log = new Logs([
            'user_id' => null,
            'event_datetime' => date('Y-m-d H:i:s'),
            'event' => Logs::EVENT_USER_OPEN_REGISTRATION_PAGE,
        ]);
        $log->description = $log->generateEventDescription();
        $log->save();

        $this->layout = 'main-login';

        $model = new RegisterForm();
        $model->rate_id = Rates::getDefaultRate();

        if ($model->load(Yii::$app->request->post()) && $model->register()) {

            $request1 = file_get_contents("http://api.sypexgeo.net/json/".$_SERVER['REMOTE_ADDR']);
            $ipCity = json_decode($request1);

            ClientController::sendTelMessage('247187885',  "Зарегистрирован новый пользователь:
                    ФИО: {$model->fio}
                    Логин: {$model->login}
                    Телефон: {$model->telephone}
                    Город: {$ipCity->city->name_ru}
                    ip: {$_SERVER['REMOTE_ADDR']}");

            $login = new LoginForm([
                'username' => $model->login,
                'password' => Yii::$app->request->post('RegisterForm')['password'],
            ]);
            $log = new Logs([
                'user_id' => Yii::$app->user->id,
                'event_datetime' => date('Y-m-d H:i:s'),
                'event' => Logs::EVENT_USER_AUTHORIZED,
            ]);
            $log->description = $log->generateEventDescription();
            $log->save();
            if ($login->login()){
                return $this->goHome();
            }

        } else {
            return $this->render('register', [
                'model' => $model,
            ]);
        }
    }

    public function actionReset()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $this->layout = 'main-login';

        $model = new ResetPasswordForm();

        if ($model->load(Yii::$app->request->post()) && $model->reset()) {
            Yii::$app->session->setFlash('register_success', 'На вашу почту был выслан временный пароль. Воспользуйтесь им для авторизации');
            return $this->redirect(['login']);
        } else {
            return $this->render('reset', [
                'model' => $model,
            ]);
        }
    }
}

views/yii2-app/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<section class="content">

    <div class="error-page">
        <h2 class="headline text-info"><i class="fa fa-warning text-yellow"></i></h2>

        <div class="error-content">
            <h3><?= $name ?></h3>

            <p>
                <?= nl2br(Html::encode($message)) ?>
            </p>

            <p>
                The above error occurred while the Web server was processing your request.
                Please contact us if you think this is a server error. Thank you.
                Meanwhile, you may <a href='<?= Yii::$app->homeUrl ?>'>return to dashboard</a> or try using the search
                form.
            </p>

            <form class='search-form'>
                <div class='input-group'>
                    <input type="text" name="search" class='form-control' placeholder="Search"/>

                    <div class="input-group-btn">
                        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</section>

views/yii2-app/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */
/* @var $slider app\models\Slider[] */

$this->title = 'Войти';

$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];

$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];

if(count($slider) > 0 && Yii::$app->mobileDetect->isMobile() == false)
{
    \app\assets\pages\LoginPageAsset::register($this);
    \app\widgets\owlCarousel\OwlCarouselAsset::register($this);
}

$image = \app\models\Settings::findByKey('home_form_image')->value;

if($image == null)
{
    $image = '';
}

?>

    <div class="login-box" style="background: url('<?=$image?>')">
        <div class="login-logo">
            <a href="#"><b>TEO-SEND</b></a>
        </div>
        <?php if(Yii::$app->session->hasFlash('register_success')): ?>
            <p>
            <div class="alert alert-success show m-b-0">
                <span class="close" data-dismiss="alert">×</span>
                <strong>Успех!</strong>
                <?=Yii::$app->session->getFlash('register_success')?>
            </div>
            </p>
        <?php endif; ?>
        <div class="login-box-body">
            <p class="login-box-msg">Введите данные авторизации</p>

            <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

            <?= $form
                ->field($model, 'username', $fieldOptions1)
                ->label(false)
                ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>

            <?= $form
                ->field($model, 'password', $fieldOptions2)
                ->label(false)
                ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>

            <div class="row">
                <div class="col-xs-9">
                    <?= $form->field($model, 'rememberMe')->checkbox()->label('Запомни меня') ?>
                </div>
                <div class="col-xs-12">
                    <?= Html::submitButton('Войти по логину и паролю', ['class' => 'btn btn-primary btn-block btn-flat',  'style' => 'width:100%', 'name' => 'login-button']) ?>
                </div>
            </div>
            <div class="row">
                <br>
                <div class="col-xs-6">
                    <p>
                        <?= Html::a('Востановить пароль', $url = '/site/reset', ['option' => 'value']); ?>
                    </p>
                </div>
                <div class="col-xs-6">
                    <p class="pull-right">
                        <?= Html::a('Зарегистрироваться', $url = '/site/register', ['option' => 'value']); ?>
                    </p>
                </div>
            </div>


            <?php ActiveForm::end(); ?>

            <!-- <div class="social-auth-links text-center">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in
                    using Facebook</a>
                <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign
                    in using Google+</a>
            </div> -->
            <!-- /.social-auth-links -->

            <!-- <a href="#">Забыл пароль</a><br> -->
            <!-- <a href="register.html" class="text-center">Register a new membership</a> -->

        </div>
        <!-- /.login-box-body -->
    </div><!-- /.login-box -->

<?php if(count($slider) > 0 && Yii::$app->mobileDetect->isMobile() == false): ?>

    <div class="slider">
        <div class="login-carousel">
            <?php foreach ($slider as $item): ?>
                <div class="item">
                    <div class="item-body">
                        <img class="item-image" src="/<?=$item->image_path?>" alt="<?=$item->image_alt?>">
                        <div class="overlay"></div>
                        <div class="item-text-content">
                            <h2><?=$item->header?></h2>
                            <p><?=$item->content?></p>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

<?php endif; ?>

<?php

$delayTime = \app\models\Settings::findByKey('slider_delay')->value;

if($delayTime == null){
    $delayTime = 10000;
}

$script = <<< JS
$('.login-carousel').owlCarousel({
    loop:true,
    nav:true,
    items: 1,
    dots: false,
    nav: false,
    autoplay:true,
    autoplayTimeout:{$delayTime},
    autoplayHoverPause:true
});
JS;

$this->registerJs($script, \yii\web\View::POS_READY);

?>